apiVersion: v1
entries:
  stocktrader-app:
  - apiVersion: v1
    created: 2018-09-06T11:21:32.451162+02:00
    description: IBM StockTrader application
    digest: b8ff9b9f2819de55f8c0c70a20581819e382f79ffbd72d9a842f72c9cb746255
    name: stocktrader-app
    urls:
    - https://raw.githubusercontent.com/vmware-ibm-jil/stocktrader-jil/v1.0/helm-chart/charts/stocktrader-app-0.2.0.tgz
    version: 0.2.0
generated: 2018-09-06T11:21:32.445077+02:00
