{{- if .Values.route.twitter.enabled }}
{{- if .Values.secret.twitter.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.twitter.secret_name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
type: Opaque
data:
  consumerKey: {{ .Values.secret.twitter.consumerKey }}
  consumerSecret: {{ .Values.secret.twitter.consumerSecret }}
  accessToken: {{ .Values.secret.twitter.accessToken }}
  accessTokenSecret: {{ .Values.secret.twitter.accessTokenSecret }}
{{- end }}
{{- end }}
